# Site settings
title: Portworx Documentation Site
email: support@portworx.com
description: > # this means to ignore newlines until "baseurl:"
  Documentation for Portworx Products
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://portworx.com" # the base hostname & protocol for your site

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty

gems: 
  - jekyll-redirect-from
